# 4.2 Universal Functions: Fast Element-Wise Array Functions

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
np.sqrt(arr)

In [4]:
np.exp(arr)

In [5]:
x = np.random.randn(8)

In [6]:
y = np.random.randn(8)

In [7]:
np.maximum(x,y)

array([-0.02935058,  0.03894915,  0.92361044, -0.05997234, -0.28664815,
        0.94919899,  1.04603296,  1.18313969])

In [8]:
np.minimum(x,y)

array([-2.15634176, -0.63751882, -0.78982823, -1.3027157 , -0.46372567,
       -0.93057307, -0.25284272, -0.029902  ])

In [9]:
np.divmod(x,y)

(array([ 73., -17.,  -2.,   0.,   0.,  -1.,  -1.,  -1.]),
 array([-0.01374932,  0.02461673, -0.65604601, -0.05997234, -0.28664815,
         0.01862593,  0.79319025,  1.15323769]))

In [10]:
np.random.randn(7) *5

array([ -0.33864471,   0.94073305, -12.98611712,   1.66108344,
         6.39698889,  -1.07791339,   0.5912091 ])

In [11]:
remaider , wholepart = np.modf(arr)

In [12]:
remaider

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
wholepart

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
h,k = np.modf(arr)

In [15]:
h

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
k

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [20]:
np.fmax(x,y)

array([-0.02935058,  0.03894915,  0.92361044, -0.05997234, -0.28664815,
        0.94919899,  1.04603296,  1.18313969])

# 4.3 Array-Oriented Programming with Arrays

In [21]:
points = np.arange(-5,5,0.01)

In [22]:
y_axis,x_axis = np.meshgrid(points,points)

In [23]:
y_axis

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [24]:
x_axis

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [25]:
z = np.sqrt(x_axis**2 + y_axis**2)

In [26]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

# Expressing Conditional Logic as Array Operations

In [27]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,False,False])
result = [(x if c else y)
         for x , y , c in zip(xarr,yarr,cond)
         ] 

In [28]:
result

[1.1, 2.2, 1.3, 2.4, 2.5]

In [29]:
result = np.where(cond,xarr,yarr)

In [30]:
result

array([1.1, 2.2, 1.3, 2.4, 2.5])

In [31]:
arr = np.random.randn(4,4)

In [32]:
arr

array([[-1.71968036, -0.13228222, -1.14923014,  0.20992013],
       [-0.67206876, -0.46813822,  0.85347556, -0.23422143],
       [-1.85315792, -0.22186683, -0.27451419,  1.0727275 ],
       [ 0.31465402, -1.27546456, -1.10060929,  2.38578414]])

In [33]:
arr>0

array([[False, False, False,  True],
       [False, False,  True, False],
       [False, False, False,  True],
       [ True, False, False,  True]])

In [34]:
np.where(arr>0,2,-2)

array([[-2, -2, -2,  2],
       [-2, -2,  2, -2],
       [-2, -2, -2,  2],
       [ 2, -2, -2,  2]])

In [35]:
np.where(arr>0,2,arr) # set only positive values to 2

array([[-1.71968036, -0.13228222, -1.14923014,  2.        ],
       [-0.67206876, -0.46813822,  2.        , -0.23422143],
       [-1.85315792, -0.22186683, -0.27451419,  2.        ],
       [ 2.        , -1.27546456, -1.10060929,  2.        ]])

# Mathematical and Statistical Methods

In [36]:
arr = np.random.randn(5,4)

In [37]:
arr

array([[-1.81444395,  0.69780447,  0.56040812,  0.31272775],
       [-0.01448459,  1.31307146, -0.20138383, -1.07131678],
       [-1.14410238, -0.151494  ,  0.45178029,  0.96797146],
       [ 1.10475277,  1.44819304, -0.26861573, -0.37827867],
       [-0.86972391,  0.18274427,  0.6469769 , -1.62940161]])

In [38]:
arr.mean()

0.0071592539509746644

In [39]:
np.mean(arr)

0.0071592539509746644

In [40]:
arr.sum()

0.1431850790194933

In [41]:
np.sum(arr)

0.1431850790194933

In [42]:
arr.mean()

0.0071592539509746644

In [43]:
np.mean(arr)

0.0071592539509746644

In [44]:
arr.mean(axis=1)

array([-0.0608759 ,  0.00647157,  0.03103884,  0.47651285, -0.41735109])

In [45]:
arr.mean(axis=0)

array([-0.54760041,  0.69806385,  0.23783315, -0.35965957])

In [46]:
arr = np.arange(10)
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [47]:
arr = np.array( [ [0,1,2],[3,4,5],[6,7,8] ] )
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [49]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

# Methods for Boolean Arrays

In [50]:
arr = np.random.randn(100)
(arr>0).sum() # Number of positive values

47

In [51]:
bools = np.array([True, False, False, False])
bools.any()


True

In [52]:
bools.all()

False

# Sorting

In [53]:
arr = np.random.randn(6)

In [54]:
arr.sort()

In [55]:
arr

array([-0.56379662, -0.23025297,  0.27174817,  0.74109816,  0.86899   ,
        2.19371616])

In [56]:
arr = np.random.randn(5,4)

In [57]:
arr

array([[ 0.90726451, -0.71824555,  0.71934966, -0.04518102],
       [ 0.66359495, -0.67855793, -0.91464626, -0.75314152],
       [-0.56838094, -0.04546103,  0.06875332, -0.84359195],
       [-0.52939   , -0.43748808,  1.0965939 ,  1.29490729],
       [ 1.34553262,  0.56797453,  0.70027988, -0.02972809]])

In [58]:
arr.sort(1)

In [59]:
arr

array([[-0.71824555, -0.04518102,  0.71934966,  0.90726451],
       [-0.91464626, -0.75314152, -0.67855793,  0.66359495],
       [-0.84359195, -0.56838094, -0.04546103,  0.06875332],
       [-0.52939   , -0.43748808,  1.0965939 ,  1.29490729],
       [-0.02972809,  0.56797453,  0.70027988,  1.34553262]])

In [60]:
large_arr = np.random.randn(1000)

large_arr.sort()

In [61]:
large_arr[int(0.05*len(large_arr))]

-1.6078010632503201

# Unique and Other Set Logic

In [62]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [63]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [64]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [65]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [66]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

# 4.4 File Input and Output with Arrays

In [67]:
arr = np.arange(10)
np.save("some_array",arr)

In [68]:
np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.savez("full_of_array",a=arr,b=arr)

In [70]:
p = np.load("full_of_array.npz")

In [71]:
p["a"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
p["b"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.savez_compressed("compressed_arrays.npz",c=arr,p=arr)

# 4.5 Linear Algebra

In [74]:
x = np.array( [ [1.,2.,3.],[4.,5.,6.], ] )
y = np.array( [ [3.,4.],[6.,7.],[9.,2.] ] )

In [75]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [76]:
y

array([[3., 4.],
       [6., 7.],
       [9., 2.]])

In [77]:
x.dot(y)

array([[42., 24.],
       [96., 63.]])

In [78]:
np.dot(x,y)

array([[42., 24.],
       [96., 63.]])

In [79]:
np.dot(x,np.ones(3))

array([ 6., 15.])

In [80]:
x @ np.ones(3)

array([ 6., 15.])

In [81]:
from numpy.linalg import inv,qr

x = np.random.randn(5,5)
mat = x.T.dot(x)
inv(mat)

array([[ 1.06079361,  0.08002984,  0.50380915, -0.56892501, -0.29267357],
       [ 0.08002984,  0.6212503 ,  0.03518314, -0.37241348,  0.23555592],
       [ 0.50380915,  0.03518314,  0.43577153, -0.26472027, -0.22504047],
       [-0.56892501, -0.37241348, -0.26472027,  0.66869978, -0.06563219],
       [-0.29267357,  0.23555592, -0.22504047, -0.06563219,  0.45006591]])

In [82]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -5.06260783e-17,  2.39150675e-16,
         9.05316236e-17,  2.63431267e-17],
       [ 1.45805227e-16,  1.00000000e+00,  1.02966116e-16,
        -2.25397836e-16, -4.66332904e-17],
       [-7.04520925e-17, -1.40866551e-16,  1.00000000e+00,
         4.18103800e-16, -1.56795228e-16],
       [ 3.81334555e-16, -2.00969797e-16,  7.67557358e-16,
         1.00000000e+00, -1.13275718e-16],
       [-1.10879683e-16,  1.99815960e-16,  5.25625855e-17,
        -1.15615727e-16,  1.00000000e+00]])

# 4.6 Pseudorandom Number Generation

In [83]:
samples = np.random.normal(size=(2,2))
samples

array([[ 0.63159346, -0.08468755],
       [ 0.59821887,  1.28358776]])

In [84]:
from random import normalvariate

In [85]:
np.random.seed(123)

In [86]:
rng = np.random.RandomState(1234)

In [87]:
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

# 4.7 Example: Random Walks